---
# openldap_server/tasks/install_packages.yml

- name: 'Install OpenLDAP server packages'
  package:
    name: "{{ openldap_server_packages }}"
    state: 'present'
  register: install_openldap_server_packages
  notify:
    - 'Stop the OpenLDAP server service'
    - 'Remove database files'
    - 'Create directories for dynamic configuration'
    - 'Remove slapd.conf if dynamic configuration is used'
    - 'Remove file olcDatabase={2}hdb.ldif'
    - 'Remove file olcDatabase={1}mdb.ldif'
    - 'Create cn=module{0}.ldif'
    - 'Create cn=module{1}.ldif'
    - 'Create olcDatabase={-1}frontend.ldif'
    - 'Create olcDatabase={1}monitor.ldif'
    - 'Create olcDatabase={2}mdb.ldif'
    - 'Remove TLS settings from cn=config.ldif'

- name: 'Install additional packages'
  package:
    name: "{{ additional_packages }}"
    state: 'present'
  register: install_additional_packages

- name: 'Set fact to ignore errors if additional_packages would be installed, but we are in check mode'
  set_fact:
     ignore_errors_when_packages_would_be_installed: 'true'
  check_mode: 'false'
  when:
    - 'install_additional_packages.changed | bool or install_openldap_server_packages.changed | bool'
    - 'ansible_check_mode | bool'

- name: 'Force all notified handlers to run at this point, not waiting for normal sync points'
  meta: flush_handlers
