---
# openldap_server/tasks/install_packages.yml

- name: 'Install OpenLDAP server packages'
  package:
    name: "{{ openldap_server_packages }}"
    state: 'present'
  notify:
    - 'Stop the OpenLDAP server service'
    - 'Remove database files'
    - 'Remove file olcDatabase={2}hdb.ldif'
    - 'Remove file olcDatabase={1}mdb.ldif'
    - 'Create cn=module{1}.ldif'
    - 'Create olcDatabase={-1}frontend.ldif'
    - 'Create olcDatabase={1}monitor.ldif'
    - 'Create olcDatabase={2}mdb.ldif'
    - 'Remove TLS settings from cn=config.ldif'

- name: 'Install additional packages'
  package:
    name: "{{ additional_packages }}"
    state: 'present'

- name: 'Force all notified handlers to run at this point, not waiting for normal sync points'
  meta: flush_handlers
