---
# openldap_server/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Install packages'
  include_tasks: install_packages.yml
  tags:
    - 'installation'

- name: 'Configure the OpenLDAP service using a static configuration'
  include_tasks:
    file: openldap_static_configuration.yml
    apply:
      tags:
        - 'configuration'
  when: 'use_static_configuration | bool'
  tags:
    - 'configuration'

- name: 'Configure the OpenLDAP service using a dynamic configuration'
  include_tasks:
    file: openldap_dynamic_configuration.yml
    apply:
      tags:
        - 'configuration'
  when: 'not use_static_configuration | bool'
  tags:
    - 'configuration'

- name: 'Start and enable the OpenLDAP service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'started'
    enabled: 'true'
