---
# openldap_server/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}{{ ansible_distribution_major_version }}.yml"
    - "vars_{{ ansible_distribution | replace(' ', '_' ) }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Parse variables'
  include_tasks:
    file: parse_variables.yml
    apply:
      tags:
        - 'installation'
        - 'configuration'
  tags:
    - 'installation'
    - 'configuration'

- name: 'Install packages'
  include_tasks:
    file: install_packages.yml
    apply:
      tags:
        - 'installation'
  tags:
    - 'installation'

- name: 'Configure the OpenLDAP service using a static configuration'
  include_tasks:
    file: openldap_static_configuration.yml
    apply:
      tags:
        - 'configuration'
  when: 'use_static_configuration | bool'
  tags:
    - 'configuration'

- name: 'Enable the OpenLDAP service'
  service:
    name: "{{ openldap_server_service }}"
    enabled: 'true'

- name: 'Start the OpenLDAP service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'started'

- name: 'Configure the OpenLDAP service using a dynamic configuration'
  include_tasks:
    file: openldap_dynamic_configuration.yml
    apply:
      tags:
        - 'configuration'
  when: 'not use_static_configuration | bool'
  tags:
    - 'configuration'

- name: 'Enable TLS when using a dynamic configuration'
  include_tasks:
    file: openldap_dynamic_configuration_enable_TLS.yml
    apply:
      tags:
        - 'configuration'
  when:
    - 'not use_static_configuration | bool'
    - 'use_tls | bool'
  tags:
    - 'configuration'

- name: 'Disable LDAPS via the sysconf or default file'
  include_tasks:
    file: openldap_disable_ldaps.yml
    apply:
      tags:
        - 'configuration'
  when:
    - 'not use_ldaps | bool'
  tags:
    - 'configuration'

- name: 'Enable LDAPS via the sysconf or default file'
  include_tasks:
    file: openldap_enable_ldaps.yml
    apply:
      tags:
        - 'configuration'
  when:
    - 'use_tls | bool'
    - 'use_ldaps | bool'
  tags:
    - 'configuration'

- name: 'Force all notified handlers to run at this point, not waiting for normal sync points'
  meta: flush_handlers
  tags:
    - 'installation'
