---
# openldap_server/tasks/main.yml

- name: "Load variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars_{{ ansible_distribution }}.yml"
    - "vars_{{ ansible_os_family }}.yml"
  tags:
    - 'installation'
    - 'configuration'

- name: 'Install packages'
  include_tasks: install_packages.yml
  tags:
    - 'installation'
