---
# openldap_server/tasks/openldap_dynamic_configuration_enable_TLS.yml

#
# enable TLS by setting
# - olcTLSCertificateFile
# - olcTLSCertificateKeyFile
# - olcTLSCaCertificateFile
#

#
# create LDIF files and apply them, if needed
#
- name: 'Create LDIF file to enable TLS'
  template:
    src: "{{ item }}.j2"
    dest: "/root/OpenLDAP_configuration_via_ansible/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - 'enable_TLS_cacertificate.ldif'
    - 'enable_TLS_certificate.ldif'
    - 'enable_TLS_key.ldif'

- name: 'Check if olcTLS is present in cn=config.ldif'
  command:
    cmd: "grep '^olcTLS' {{ path_to_openldap_etc_directory }}slapd.d/cn=config.ldif"
  register: grep_for_olcTLS_in_config
  check_mode: 'false'
  changed_when: 'false'
  failed_when: 'grep_for_olcTLS_in_config.rc != 0 and grep_for_olcTLS_in_config.stdout != ""'

- name: 'Set database ACLs via ldapmodify'
  command:
    cmd: "ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/OpenLDAP_configuration_via_ansible/{{ item.file }}"
  loop:
    - name: "{{ ('olcTLSCertificateFile: ' + path_to_TLS_certificate) | truncate(75, True, '', 0) }}"
      file: 'enable_TLS_certificate.ldif'
    - name: "{{ ('olcTLSCertificateKeyFile: ' + path_to_TLS_key) | truncate(75, True, '', 0) }}"
      file: 'enable_TLS_key.ldif'
    - name: "{{ ('olcTLSCACertificateFile: ' + path_to_TLS_ca_certificate) | truncate(75, True, '', 0) }}"
      file: 'enable_TLS_cacertificate.ldif'
  when: 'item.name not in grep_for_olcTLS_in_config.stdout'
  tags:
    - 'configuration'
