---
# openldap_server/tasks/openldap_dynamic_configuration_enable_TLS.yml

#
# enable TLS by setting
# - olcTLSCertificateFile
# - olcTLSCertificateKeyFile
# - olcTLSCaCertificateFile
#

#
# Create the directory for the LDIF files in case it is missing
#
- name: 'Create directory /root/OpenLDAP_configuration_via_ansible/'
  file:
    path: '/root/OpenLDAP_configuration_via_ansible/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'

#
# Pre-flight checks
#
- fail:
    msg: 'path_to_TLS_certificate and TLS_certificate_filename are both undefined'
  when: 'path_to_TLS_certificate is undefined and TLS_certificate_filename is undefined'

- fail:
    msg: 'path_to_TLS_key and TLS_key_filename are both undefined'
  when: 'path_to_TLS_key is undefined and TLS_key_filename is undefined'

- fail:
    msg: 'path_to_TLS_ca_certificate and TLS_ca_certificate_filename are both undefined'
  when: 'path_to_TLS_ca_certificate is undefined and TLS_ca_certificate_filename is undefined'

#
# define variables for full paths to TLS files
#
- name: 'Build full path to TLS files'
  set_fact:
    path_to_TLS_certificate: "{{ path_to_openldap_etc_directory }}certs/{{ TLS_certificate_filename }}"
  when: 'path_to_TLS_certificate is undefined'

- name: 'Build full path to TLS files'
  set_fact:
    path_to_TLS_key: "{{ path_to_openldap_etc_directory }}certs/{{ TLS_key_filename }}"
  when: 'path_to_TLS_key is undefined'

- name: 'Build full path to TLS files'
  set_fact:
    path_to_TLS_ca_certificate: "{{ path_to_openldap_etc_directory }}certs/{{ TLS_ca_certificate_filename }}"
  when: 'path_to_TLS_ca_certificate is undefined'

#
# Fail if certificate files are missing
#

- name: 'Check for the certificate files'
  stat:
    path: 'item'
  register: check_for_certificate_files
  loop:
    - "{{ path_to_TLS_certificate }}"
    - "{{ path_to_TLS_key }}"
    - "{{ path_to_TLS_ca_certificate }}"

- fail:
    msg: "{{ item }} is missing..."
  loop: "{{ check_for_certificate_files.results }}"
  when: 'item.stat.exists | bool'

#
# apply the TLS settings
#
- name: 'Add TLS setting'
  ldap_attr:
    dn: 'cn=config'
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: 'exact'
  loop:
    - name: 'olcTLSCACertificateFile'
      value: "{{ path_to_TLS_ca_certificate }}"
    - name: 'olcTLSCertificateKeyFile'
      value: "{{ path_to_TLS_key }}"
    - name: 'olcTLSCertificateFile'
      value: "{{ path_to_TLS_certificate }}"
  tags:
    - 'configuration'
