---
# openldap_server/tasks/openldap_dynamic_configuration.yml

#
# Make sure all necessary schemas are imported/present
#

- name: 'Create necessary schemas'
  command:
    cmd: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f {{ path_to_openldap_etc_directory }}schema/{{ item.source }}"
    creates: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/cn=schema/{{ item.target }}"
  loop:
    - source: 'cosine.ldif'
      target: 'cn={1}cosine.ldif'
    - source: 'nis.ldif'
      target: 'cn={2}nis.ldif'
    - source: 'inetorgperson.ldif'
      target: 'cn={3}inetorgperson.ldif'
  tags:
    - 'configuration'

#
# Set olcRootPW for olcDatabase={0}config,cn=config
#

- name: 'Create directory /root/OpenLDAP_configuration_via_ansible/'
  file:
    path: '/root/OpenLDAP_configuration_via_ansible/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  notify:
    - 'Fix permissions on database files'
    - 'Restart the OpenLDAP server service'

- name: 'Create LDIF file to set olcRootPW'
  template:
    src: 'rootDN_password_hash.ldif.j2'
    dest: '/root/OpenLDAP_configuration_via_ansible/rootDN_password_hash.ldif'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Check if olcRootPW is present'
  command:
    # we really grep for the base64-encoded hash
    cmd: "grep 'olcRootPW:: {{ password_hash_base64_rootdn }}' {{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={0}config.ldif"
  register: grep_for_olcRootPW
  check_mode: 'false'
  changed_when: 'grep_for_olcRootPW.rc == 1 and grep_for_olcRootPW.stdout == ""'
  failed_when: 'grep_for_olcRootPW.rc != 0 and grep_for_olcRootPW.stdout != ""'

- name: 'Set olcRootPW via ldapmodify'
  command:
    cmd: 'ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/OpenLDAP_configuration_via_ansible/rootDN_password_hash.ldif'
  when: 'grep_for_olcRootPW.stdout == ""'
  tags:
    - 'configuration'

#
# Set the loglevel in olcDatabase={0}config,cn=config
#

- name: 'Create LDIF file to set olcLogLevel'
  template:
    src: 'loglevel.ldif.j2'
    dest: '/root/OpenLDAP_configuration_via_ansible/loglevel.ldif'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Check if olcLogLevel is present'
  command:
    cmd: "grep 'olcLogLevel: {{ slapd_loglevel }}' {{ path_to_openldap_etc_directory }}slapd.d/cn=config.ldif"
  register: grep_for_olcLogLevel
  check_mode: 'false'
  changed_when: 'grep_for_olcLogLevel.rc == 1 and grep_for_olcLogLevel.stdout == ""'
  failed_when: 'grep_for_olcLogLevel.rc != 0 and grep_for_olcLogLevel.stdout != ""'

- name: 'Set olcLogLevel via ldapmodify'
  command:
    cmd: 'ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/OpenLDAP_configuration_via_ansible/loglevel.ldif'
  when: 'grep_for_olcLogLevel.stdout == ""'
  changed_when: 
  tags:
    - 'configuration'

#
# Set frontend ACLs
#

- name: 'Create LDIF file to set the frontend ACLs'
  template:
    src: "{{ item }}.j2"
    dest: "/root/OpenLDAP_configuration_via_ansible/{{ item }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - 'frontend_acl_0.ldif'
    - 'frontend_acl_1.ldif'
    - 'frontend_acl_2.ldif'
    - 'frontend_acl_3.ldif'
    - 'frontend_acl_4.ldif'

- name: 'Check if olcAccess is present in olcDatabase={-1}frontend.ldif'
  command:
    cmd: "grep '^olcAccess:' {{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={-1}frontend.ldif"
  register: grep_for_olcAccess
  check_mode: 'false'
  changed_when: 'false'
  failed_when: 'grep_for_olcAccess.rc != 0 and grep_for_olcAccess.stdout != ""'

- name: 'Set frontend ACLs via ldapmodify'
  command:
    cmd: "ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/OpenLDAP_configuration_via_ansible/{{ item.file }}"
  loop:
    - name: 'olcAccess: {0}to'
      file: 'frontend_acl_0.ldif'
    - name: 'olcAccess: {1}to'
      file: 'frontend_acl_1.ldif'
    - name: 'olcAccess: {2}to'
      file: 'frontend_acl_2.ldif'
    - name: 'olcAccess: {3}to'
      file: 'frontend_acl_3.ldif'
    - name: 'olcAccess: {4}to'
      file: 'frontend_acl_4.ldif'
  when: 'item.name not in grep_for_olcAccess.stdout'
  tags:
    - 'configuration'
