---
# openldap_server/tasks/openldap_enable_ldaps.yml

- name: 'Enable LDAPS in the sysconfig or default file'
  lineinfile:
    path: "{{ path_to_sysconfig_file }}"
    regex: '^SLAPD_SERVICES='
    line: 'SLAPD_SERVICES="ldap:/// ldaps:/// ldapi:///"'
  notify:
    - 'Restart the OpenLDAP server service'
