---
# openldap_server/tasks/openldap_dynamic_configuration.yml

#
# Make sure all necessary schemas are imported/present
#

- name: 'Create necessary schemas'
  command:
    cmd: "ldapadd -Q -Y EXTERNAL -H ldapi:/// -f {{ path_to_openldap_etc_directory }}schema/{{ item.source }}"
    creates: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/cn=schema/{{ item.target }}"
  loop:
    - source: 'cosine.ldif'
      target: 'cn={1}cosine.ldif'
    - source: 'nis.ldif'
      target: 'cn={2}nis.ldif'
    - source: 'inetorgperson.ldif'
      target: 'cn={3}inetorgperson.ldif'
  tags:
    - 'configuration'

#
# Set olcRootPW for olcDatabase={0}config,cn=config
#

- name: 'Create directory /root/OpenLDAP_configuration_via_ansible/'
  file:
    path: '/root/OpenLDAP_configuration_via_ansible/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
  notify:
    - 'Fix permissions on database files'
    - 'Restart the OpenLDAP server service'

- name: 'Create ldif file for import via slapadd'
  template:
    src: 'initial_state_via_slapadd.ldif.j2'
    dest: '/root/OpenLDAP_configuration_via_ansible/initial_state_via_slapadd.ldif'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Fix permissions on database files'
    - 'Restart the OpenLDAP server service'
    - 'Set olcRootPW via ldapmodify'

- name: 'Import the initial state via slapadd'
  command:
    cmd: '/usr/sbin/slapadd -l /root/OpenLDAP_configuration_via_ansible/initial_state_via_slapadd.ldif'
    creates: '/var/lib/ldap/data.mdb'
  notify:
    - 'Fix permissions on database files'
    - 'Restart the OpenLDAP server service'
    - 'Set olcRootPW via ldapmodify'

- name: 'Create LDIF file to set olcRootPW'
  template:
    src: 'rootDN_password_hash.ldif.j2'
    dest: '/root/OpenLDAP_configuration_via_ansible/rootDN_password_hash.ldif'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify:
    - 'Set olcRootPW via ldapmodify'

- name: 'Check if olcRootPW is present'
  command:
    # we really grep for the base64-encoded hash
    cmd: "grep 'olcRootPW:: {{ password_hash_base64_rootdn }}' {{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={0}config.ldif"
  register: grep_for_olcRootPW
  check_mode: 'false'
  changed_when: 'grep_for_olcRootPW.rc == 1 and grep_for_olcRootPW.stdout == ""'
  failed_when: 'grep_for_olcRootPW.rc != 0 and grep_for_olcRootPW.stdout != ""'
  notify:
    - 'Set olcRootPW via ldapmodify'

- debug:
    var: grep_for_olcRootPW
