---
# openldap_server/handlers/main.yml

#
# handlers triggered by package installation
#
- name: 'Stop the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

