---
# openldap_server/handlers/main.yml

#
# handlers triggered by package installation
#
- name: 'Stop the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

- name: 'Remove database files'
  file:
    path: "{{ item }}"
    state: 'absent'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  tags:
    - 'installation'

#
# handlers triggered by configuration changes
#
- name: 'Fix permissions on database files'
  file:
    path: "{{ item }}"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - 'configuration'
  notify:
    - 'Restart the OpenLDAP server service'

- name: 'Restart the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'restarted'
  tags:
    - 'configuration'

- name: 'Set olcRootPW via ldapmodify'
  command:
    cmd: 'ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f /root/OpenLDAP_configuration_via_ansible/rootDN_password_hash_base64.ldif'
  when: 'grep_for_olcRootPW.stdout == ""'
  tags:
    - 'configuration'
