---
# openldap_server/handlers/main.yml

#
# handlers triggered by package installation
#
- name: 'Stop the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

- name: 'Remove database files'
  file:
    path: "{{ item }}"
    state: 'absent'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  tags:
    - 'installation'

#
# include handlers for dynamic or static configuration
#
- name: 'Include handlers for dynamic configuration'
  import_tasks: dynamic_configuration.yml
  when:
    - 'not use_static_configuration | bool'

- name: 'Include handlers for static configuration'
  import_tasks: static_configuration.yml
  when:
    - 'use_static_configuration | bool'

#
# handlers triggered by configuration changes
#
- name: 'Restart the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'restarted'
  tags:
    - 'configuration'
