---
# openldap_server/handlers/main.yml

#
# handlers triggered by package installation
#
- name: 'Stop the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

- name: 'Remove database files'
  file:
    path: "{{ item }}"
    state: 'absent'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  tags:
    - 'installation'
