---
# openldap_server/handlers/main.yml

#
# handlers triggered by package installation
#
- name: 'Stop the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'stopped'
    masked: 'false'
  tags:
    - 'installation'

- name: 'Remove database files'
  file:
    path: "{{ item }}"
    state: 'absent'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  tags:
    - 'installation'

- name: 'Remove file olcDatabase={2}hdb.ldif'
  file:
    path: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={2}hdb.ldif"
    state: 'absent'
  when: 'ansible_os_family == "RedHat"'
  tags:
    - 'installation'

- name: 'Remove file olcDatabase={1}mdb.ldif'
  file:
    path: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={1}mdb.ldif"
    state: 'absent'
  when: 'ansible_os_family == "Debian"'
  tags:
    - 'installation'

- name: 'Create cn=module{1}.ldif'
  template:
    src: 'cn_module1.ldif.j2'
    dest: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/cn=module{1}.ldif"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  when: 'ansible_os_family == "Debian"'
  tags:
    - 'installation'

- name: 'Create olcDatabase={-1}frontend.ldif'
  template:
    src: 'olcDatabase-1frontend.ldif.j2'
    dest: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={-1}frontend.ldif"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  when: 'ansible_os_family == "RedHat" or ansible_os_family == "Debian"'
  tags:
    - 'installation'

- name: 'Create olcDatabase={1}monitor.ldif'
  template:
    src: 'olcDatabase1monitor.ldif.j2'
    dest: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={1}monitor.ldif"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  when: 'ansible_os_family == "RedHat" or ansible_os_family == "Debian"'
  tags:
    - 'installation'

- name: 'Create olcDatabase={2}mdb.ldif'
  template:
    src: 'olcDatabase2mdb.ldif.j2'
    dest: "{{ path_to_openldap_etc_directory }}slapd.d/cn=config/olcDatabase={2}mdb.ldif"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  when: 'ansible_os_family == "RedHat" or ansible_os_family == "Debian"'
  tags:
    - 'installation'

- name: 'Remove TLS settings from cn=config.ldif'
  lineinfile:
    path: '/etc/openldap/slapd.d/cn=config.ldif'
    regex: ^olcTLS|CRC
    state: 'absent'
  when: 'ansible_os_family == "RedHat" and not use_tls | bool'
  tags:
    - 'installation'

#
# handlers triggered by configuration changes
#
- name: 'Fix permissions on database files'
  file:
    path: "{{ item }}"
    owner: "{{ openldap_user }}"
    group: "{{ openldap_group }}"
    mode: '0600'
  loop:
    - "{{ path_to_openldap_var_directory }}data.mdb"
    - "{{ path_to_openldap_var_directory }}lock.mdb"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - 'configuration'
  notify:
    - 'Restart the OpenLDAP server service'

- name: 'Restart the OpenLDAP server service'
  service:
    name: "{{ openldap_server_service }}"
    state: 'restarted'
  tags:
    - 'configuration'
